AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - bin/**
    - db/migrate/*
    - db/schema.rb
    - log/**
    - tmp/**
    - vendor/**

LineLength:
  Max: 120

Documentation:
  Exclude:
    - app/controllers/*
